[project]
name = "videodownloader"
version = "1.0.0"
description = "Video Downloader Android App"
requires-python = ">=3.10"
dependencies = [
    "flet",
    "yt-dlp"
]

[tool.flet]
org = "com.trustrankseo"
product = "VideoDownloader"
company = "Zubair Abbas"
copyright = "Copyright 2026"

[tool.flet.app]
path = "."
